name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run ktlintCheck
      run: ./gradlew ktlintCheck
    - name: Run dependencyGuard
      run: ./gradlew dependencyGuard
    - name: Run apiCheck
      run: ./gradlew apiCheck
    - name: Run koverHtmlReport
      run: ./gradlew koverHtmlReport
    - name: Run dokkaGenerate
      run: ./gradlew dokkaGenerate

